[2025-10-05T09:08:19.182+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-05T09:08:19.192+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: forest_cover_mlops_pipeline.train_and_log_models scheduled__2025-10-05T09:00:00+00:00 [queued]>
[2025-10-05T09:08:19.196+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: forest_cover_mlops_pipeline.train_and_log_models scheduled__2025-10-05T09:00:00+00:00 [queued]>
[2025-10-05T09:08:19.196+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 3
[2025-10-05T09:08:19.203+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): train_and_log_models> on 2025-10-05 09:00:00+00:00
[2025-10-05T09:08:19.209+0000] {standard_task_runner.py:72} INFO - Started process 6045 to run task
[2025-10-05T09:08:19.211+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'forest_cover_mlops_pipeline', 'train_and_log_models', 'scheduled__2025-10-05T09:00:00+00:00', '--job-id', '106', '--raw', '--subdir', 'DAGS_FOLDER/forest_cover_dag.py', '--cfg-path', '/home/airflow/tmp/tmpddkmy_20']
[2025-10-05T09:08:19.212+0000] {standard_task_runner.py:105} INFO - Job 106: Subtask train_and_log_models
[2025-10-05T09:08:19.254+0000] {task_command.py:467} INFO - Running <TaskInstance: forest_cover_mlops_pipeline.train_and_log_models scheduled__2025-10-05T09:00:00+00:00 [running]> on host 3702e9b7dcde
[2025-10-05T09:08:19.687+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mlops-team' AIRFLOW_CTX_DAG_ID='forest_cover_mlops_pipeline' AIRFLOW_CTX_TASK_ID='train_and_log_models' AIRFLOW_CTX_EXECUTION_DATE='2025-10-05T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-05T09:00:00+00:00'
[2025-10-05T09:08:19.687+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-05T09:08:19.945+0000] {logging_mixin.py:190} INFO - Entrenando 3 modelos con GridSearchCV...
[2025-10-05T09:08:19.945+0000] {logging_mixin.py:190} INFO - 
==================================================
[2025-10-05T09:08:19.945+0000] {logging_mixin.py:190} INFO - Modelo: RandomForest
[2025-10-05T09:08:19.945+0000] {logging_mixin.py:190} INFO - ==================================================
[2025-10-05T09:08:19.960+0000] {logging_mixin.py:190} WARNING - 2025/10/05 09:08:19 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-10-05T09:08:20.011+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.11/site-packages/joblib/parallel.py:1379: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  n_jobs = self._backend.configure(

[2025-10-05T09:08:20.011+0000] {logging_mixin.py:190} INFO - Fitting 3 folds for each of 12 candidates, totalling 36 fits
[2025-10-05T09:09:32.589+0000] {logging_mixin.py:190} INFO -   Mejores par√°metros: {'classifier__max_depth': None, 'classifier__min_samples_split': 2, 'classifier__n_estimators': 100}
[2025-10-05T09:09:41.315+0000] {logging_mixin.py:190} INFO -   Train Accuracy: 1.0000
[2025-10-05T09:09:41.315+0000] {logging_mixin.py:190} INFO -   Test Accuracy: 0.9800
[2025-10-05T09:09:41.315+0000] {logging_mixin.py:190} INFO -   Test F1 (weighted): 0.9799
[2025-10-05T09:09:41.315+0000] {logging_mixin.py:190} INFO -   CV Score: 0.9712 (+/- 0.0003)
[2025-10-05T09:09:43.432+0000] {logging_mixin.py:190} WARNING - 2025/10/05 09:09:43 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-10-05T09:09:43.488+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2025-10-05T09:09:43.765+0000] {logging_mixin.py:190} WARNING - Registered model 'forest_cover_randomforest' already exists. Creating a new version of this model...
[2025-10-05T09:09:43.780+0000] {logging_mixin.py:190} WARNING - 2025/10/05 09:09:43 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: forest_cover_randomforest, version 10
[2025-10-05T09:09:43.780+0000] {logging_mixin.py:190} WARNING - Created version '10' of model 'forest_cover_randomforest'.
[2025-10-05T09:09:43.792+0000] {logging_mixin.py:190} WARNING - 2025/10/05 09:09:43 INFO mlflow.tracking._tracking_service.client: üèÉ View run RandomForest_batch_9 at: http://mlflow:5000/#/experiments/1/runs/bf0f8a937efd431d8b86bd53aa9ea57c.
[2025-10-05T09:09:43.793+0000] {logging_mixin.py:190} WARNING - 2025/10/05 09:09:43 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow:5000/#/experiments/1.
[2025-10-05T09:09:43.803+0000] {logging_mixin.py:190} INFO - 
==================================================
[2025-10-05T09:09:43.803+0000] {logging_mixin.py:190} INFO - Modelo: GradientBoosting
[2025-10-05T09:09:43.803+0000] {logging_mixin.py:190} INFO - ==================================================
[2025-10-05T09:09:43.876+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.11/site-packages/joblib/parallel.py:1379: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  n_jobs = self._backend.configure(

[2025-10-05T09:09:43.876+0000] {logging_mixin.py:190} INFO - Fitting 3 folds for each of 8 candidates, totalling 24 fits
[2025-10-05T09:20:01.096+0000] {logging_mixin.py:190} INFO -   Mejores par√°metros: {'classifier__learning_rate': 0.1, 'classifier__max_depth': 5, 'classifier__n_estimators': 100}
[2025-10-05T09:21:58.450+0000] {logging_mixin.py:190} INFO -   Train Accuracy: 0.9711
[2025-10-05T09:21:58.450+0000] {logging_mixin.py:190} INFO -   Test Accuracy: 0.9532
[2025-10-05T09:21:58.450+0000] {logging_mixin.py:190} INFO -   Test F1 (weighted): 0.9531
[2025-10-05T09:21:58.450+0000] {logging_mixin.py:190} INFO -   CV Score: 0.9485 (+/- 0.0011)
[2025-10-05T09:21:59.975+0000] {logging_mixin.py:190} WARNING - 2025/10/05 09:21:59 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-10-05T09:22:00.034+0000] {logging_mixin.py:190} WARNING - Registered model 'forest_cover_gradientboosting' already exists. Creating a new version of this model...
[2025-10-05T09:22:00.048+0000] {logging_mixin.py:190} WARNING - 2025/10/05 09:22:00 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: forest_cover_gradientboosting, version 10
[2025-10-05T09:22:00.048+0000] {logging_mixin.py:190} WARNING - Created version '10' of model 'forest_cover_gradientboosting'.
[2025-10-05T09:22:00.055+0000] {logging_mixin.py:190} WARNING - 2025/10/05 09:22:00 INFO mlflow.tracking._tracking_service.client: üèÉ View run GradientBoosting_batch_9 at: http://mlflow:5000/#/experiments/1/runs/21a8424d8d1f449d8edb8be4fe26acab.
[2025-10-05T09:22:00.055+0000] {logging_mixin.py:190} WARNING - 2025/10/05 09:22:00 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow:5000/#/experiments/1.
[2025-10-05T09:22:00.063+0000] {logging_mixin.py:190} INFO - 
==================================================
[2025-10-05T09:22:00.063+0000] {logging_mixin.py:190} INFO - Modelo: LogisticRegression
[2025-10-05T09:22:00.063+0000] {logging_mixin.py:190} INFO - ==================================================
[2025-10-05T09:22:00.115+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.11/site-packages/joblib/parallel.py:1379: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  n_jobs = self._backend.configure(

[2025-10-05T09:22:00.115+0000] {logging_mixin.py:190} INFO - Fitting 3 folds for each of 6 candidates, totalling 18 fits
[2025-10-05T09:22:53.095+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[2025-10-05T09:23:01.572+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[2025-10-05T09:23:09.666+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[2025-10-05T09:23:22.166+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[2025-10-05T09:23:22.167+0000] {logging_mixin.py:190} INFO -   Mejores par√°metros: {'classifier__C': 10.0, 'classifier__solver': 'saga'}
[2025-10-05T09:23:30.122+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[2025-10-05T09:23:38.378+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[2025-10-05T09:23:46.515+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[2025-10-05T09:23:46.518+0000] {logging_mixin.py:190} INFO -   Train Accuracy: 0.7641
[2025-10-05T09:23:46.518+0000] {logging_mixin.py:190} INFO -   Test Accuracy: 0.7690
[2025-10-05T09:23:46.518+0000] {logging_mixin.py:190} INFO -   Test F1 (weighted): 0.7588
[2025-10-05T09:23:46.518+0000] {logging_mixin.py:190} INFO -   CV Score: 0.7636 (+/- 0.0013)
[2025-10-05T09:23:48.038+0000] {logging_mixin.py:190} WARNING - 2025/10/05 09:23:48 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-10-05T09:23:48.110+0000] {logging_mixin.py:190} WARNING - Registered model 'forest_cover_logisticregression' already exists. Creating a new version of this model...
[2025-10-05T09:23:48.149+0000] {logging_mixin.py:190} WARNING - 2025/10/05 09:23:48 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: forest_cover_logisticregression, version 10
[2025-10-05T09:23:48.149+0000] {logging_mixin.py:190} WARNING - Created version '10' of model 'forest_cover_logisticregression'.
[2025-10-05T09:23:48.177+0000] {logging_mixin.py:190} WARNING - 2025/10/05 09:23:48 INFO mlflow.tracking._tracking_service.client: üèÉ View run LogisticRegression_batch_9 at: http://mlflow:5000/#/experiments/1/runs/161656a24b7f49e9bb9645dbc8ebd7df.
[2025-10-05T09:23:48.177+0000] {logging_mixin.py:190} WARNING - 2025/10/05 09:23:48 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow:5000/#/experiments/1.
[2025-10-05T09:23:48.199+0000] {logging_mixin.py:190} INFO - 
==================================================
[2025-10-05T09:23:48.199+0000] {logging_mixin.py:190} INFO - ‚úì Entrenamiento completado
[2025-10-05T09:23:48.200+0000] {logging_mixin.py:190} INFO -   Mejor modelo: RandomForest (Accuracy: 0.9800)
[2025-10-05T09:23:48.200+0000] {logging_mixin.py:190} INFO - ==================================================
[2025-10-05T09:23:48.201+0000] {python.py:240} INFO - Done. Returned value was: {'results': {'RandomForest': {'test_accuracy': 0.9800344234079174, 'test_f1_weighted': 0.9799446684406347, 'cv_mean_score': 0.9711703963053718, 'best_params': {'classifier__max_depth': None, 'classifier__min_samples_split': 2, 'classifier__n_estimators': 100}}, 'GradientBoosting': {'test_accuracy': 0.953184165232358, 'test_f1_weighted': 0.9531125692333331, 'cv_mean_score': 0.9485154937259871, 'best_params': {'classifier__learning_rate': 0.1, 'classifier__max_depth': 5, 'classifier__n_estimators': 100}}, 'LogisticRegression': {'test_accuracy': 0.7690189328743545, 'test_f1_weighted': 0.7587773792482589, 'cv_mean_score': 0.7635972824751976, 'best_params': {'classifier__C': 10.0, 'classifier__solver': 'saga'}}}, 'best_model': 'RandomForest', 'best_score': 0.9800344234079174, 'experiment_name': 'forest_cover_classification', 'mlflow_uri': 'http://mlflow:5000'}
[2025-10-05T09:23:48.253+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-05T09:23:48.253+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=forest_cover_mlops_pipeline, task_id=train_and_log_models, run_id=scheduled__2025-10-05T09:00:00+00:00, execution_date=20251005T090000, start_date=20251005T090819, end_date=20251005T092348
[2025-10-05T09:23:48.292+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-05T09:23:48.303+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-05T09:23:48.304+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
