[2025-10-05T08:01:21.442+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-05T08:01:21.455+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: forest_cover_mlops_pipeline.train_and_log_models scheduled__2025-10-05T07:55:00+00:00 [queued]>
[2025-10-05T08:01:21.461+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: forest_cover_mlops_pipeline.train_and_log_models scheduled__2025-10-05T07:55:00+00:00 [queued]>
[2025-10-05T08:01:21.461+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 3
[2025-10-05T08:01:21.467+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): train_and_log_models> on 2025-10-05 07:55:00+00:00
[2025-10-05T08:01:21.473+0000] {standard_task_runner.py:72} INFO - Started process 1509 to run task
[2025-10-05T08:01:21.476+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'forest_cover_mlops_pipeline', 'train_and_log_models', 'scheduled__2025-10-05T07:55:00+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/forest_cover_dag.py', '--cfg-path', '/home/airflow/tmp/tmpi1karg7g']
[2025-10-05T08:01:21.477+0000] {standard_task_runner.py:105} INFO - Job 64: Subtask train_and_log_models
[2025-10-05T08:01:21.527+0000] {task_command.py:467} INFO - Running <TaskInstance: forest_cover_mlops_pipeline.train_and_log_models scheduled__2025-10-05T07:55:00+00:00 [running]> on host 3702e9b7dcde
[2025-10-05T08:01:21.814+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mlops-team' AIRFLOW_CTX_DAG_ID='forest_cover_mlops_pipeline' AIRFLOW_CTX_TASK_ID='train_and_log_models' AIRFLOW_CTX_EXECUTION_DATE='2025-10-05T07:55:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-05T07:55:00+00:00'
[2025-10-05T08:01:21.814+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-05T08:01:21.969+0000] {logging_mixin.py:190} INFO - Entrenando 3 modelos con GridSearchCV...
[2025-10-05T08:01:21.969+0000] {logging_mixin.py:190} INFO - 
==================================================
[2025-10-05T08:01:21.970+0000] {logging_mixin.py:190} INFO - Modelo: RandomForest
[2025-10-05T08:01:21.970+0000] {logging_mixin.py:190} INFO - ==================================================
[2025-10-05T08:01:21.989+0000] {logging_mixin.py:190} WARNING - 2025/10/05 08:01:21 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-10-05T08:01:22.049+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.11/site-packages/joblib/parallel.py:1379: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  n_jobs = self._backend.configure(

[2025-10-05T08:01:22.049+0000] {logging_mixin.py:190} INFO - Fitting 3 folds for each of 12 candidates, totalling 36 fits
[2025-10-05T08:01:44.841+0000] {logging_mixin.py:190} INFO -   Mejores par√°metros: {'classifier__max_depth': None, 'classifier__min_samples_split': 2, 'classifier__n_estimators': 100}
[2025-10-05T08:01:47.515+0000] {logging_mixin.py:190} INFO -   Train Accuracy: 1.0000
[2025-10-05T08:01:47.515+0000] {logging_mixin.py:190} INFO -   Test Accuracy: 0.9472
[2025-10-05T08:01:47.515+0000] {logging_mixin.py:190} INFO -   Test F1 (weighted): 0.9468
[2025-10-05T08:01:47.515+0000] {logging_mixin.py:190} INFO -   CV Score: 0.9294 (+/- 0.0035)
[2025-10-05T08:01:49.601+0000] {logging_mixin.py:190} WARNING - 2025/10/05 08:01:49 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-10-05T08:01:49.651+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2025-10-05T08:01:49.882+0000] {logging_mixin.py:190} WARNING - Registered model 'forest_cover_randomforest' already exists. Creating a new version of this model...
[2025-10-05T08:01:49.899+0000] {logging_mixin.py:190} WARNING - 2025/10/05 08:01:49 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: forest_cover_randomforest, version 3
[2025-10-05T08:01:49.900+0000] {logging_mixin.py:190} WARNING - Created version '3' of model 'forest_cover_randomforest'.
[2025-10-05T08:01:49.913+0000] {logging_mixin.py:190} WARNING - 2025/10/05 08:01:49 INFO mlflow.tracking._tracking_service.client: üèÉ View run RandomForest_batch_2 at: http://mlflow:5000/#/experiments/1/runs/ba91964293be4e5f8dc9f7a538e8b905.
[2025-10-05T08:01:49.913+0000] {logging_mixin.py:190} WARNING - 2025/10/05 08:01:49 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow:5000/#/experiments/1.
[2025-10-05T08:01:49.923+0000] {logging_mixin.py:190} INFO - 
==================================================
[2025-10-05T08:01:49.924+0000] {logging_mixin.py:190} INFO - Modelo: GradientBoosting
[2025-10-05T08:01:49.924+0000] {logging_mixin.py:190} INFO - ==================================================
[2025-10-05T08:01:50.023+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.11/site-packages/joblib/parallel.py:1379: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  n_jobs = self._backend.configure(

[2025-10-05T08:01:50.024+0000] {logging_mixin.py:190} INFO - Fitting 3 folds for each of 8 candidates, totalling 24 fits
[2025-10-05T08:05:09.292+0000] {logging_mixin.py:190} INFO -   Mejores par√°metros: {'classifier__learning_rate': 0.1, 'classifier__max_depth': 5, 'classifier__n_estimators': 100}
[2025-10-05T08:05:46.599+0000] {logging_mixin.py:190} INFO -   Train Accuracy: 0.9834
[2025-10-05T08:05:46.599+0000] {logging_mixin.py:190} INFO -   Test Accuracy: 0.9383
[2025-10-05T08:05:46.600+0000] {logging_mixin.py:190} INFO -   Test F1 (weighted): 0.9380
[2025-10-05T08:05:46.600+0000] {logging_mixin.py:190} INFO -   CV Score: 0.9230 (+/- 0.0024)
[2025-10-05T08:05:48.091+0000] {logging_mixin.py:190} WARNING - 2025/10/05 08:05:48 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-10-05T08:05:48.153+0000] {logging_mixin.py:190} WARNING - Registered model 'forest_cover_gradientboosting' already exists. Creating a new version of this model...
[2025-10-05T08:05:48.167+0000] {logging_mixin.py:190} WARNING - 2025/10/05 08:05:48 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: forest_cover_gradientboosting, version 3
[2025-10-05T08:05:48.167+0000] {logging_mixin.py:190} WARNING - Created version '3' of model 'forest_cover_gradientboosting'.
[2025-10-05T08:05:48.176+0000] {logging_mixin.py:190} WARNING - 2025/10/05 08:05:48 INFO mlflow.tracking._tracking_service.client: üèÉ View run GradientBoosting_batch_2 at: http://mlflow:5000/#/experiments/1/runs/cefc2b8ecb3b4427927bad1d15af9c34.
[2025-10-05T08:05:48.176+0000] {logging_mixin.py:190} WARNING - 2025/10/05 08:05:48 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow:5000/#/experiments/1.
[2025-10-05T08:05:48.185+0000] {logging_mixin.py:190} INFO - 
==================================================
[2025-10-05T08:05:48.185+0000] {logging_mixin.py:190} INFO - Modelo: LogisticRegression
[2025-10-05T08:05:48.185+0000] {logging_mixin.py:190} INFO - ==================================================
[2025-10-05T08:05:48.243+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.11/site-packages/joblib/parallel.py:1379: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  n_jobs = self._backend.configure(

[2025-10-05T08:05:48.243+0000] {logging_mixin.py:190} INFO - Fitting 3 folds for each of 6 candidates, totalling 18 fits
[2025-10-05T08:06:07.080+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[2025-10-05T08:06:09.513+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[2025-10-05T08:06:11.691+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[2025-10-05T08:06:15.049+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[2025-10-05T08:06:15.050+0000] {logging_mixin.py:190} INFO -   Mejores par√°metros: {'classifier__C': 10.0, 'classifier__solver': 'saga'}
[2025-10-05T08:06:17.230+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[2025-10-05T08:06:19.411+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[2025-10-05T08:06:21.729+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[2025-10-05T08:06:21.731+0000] {logging_mixin.py:190} INFO -   Train Accuracy: 0.7654
[2025-10-05T08:06:21.731+0000] {logging_mixin.py:190} INFO -   Test Accuracy: 0.7665
[2025-10-05T08:06:21.731+0000] {logging_mixin.py:190} INFO -   Test F1 (weighted): 0.7560
[2025-10-05T08:06:21.732+0000] {logging_mixin.py:190} INFO -   CV Score: 0.7648 (+/- 0.0033)
[2025-10-05T08:06:23.249+0000] {logging_mixin.py:190} WARNING - 2025/10/05 08:06:23 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-10-05T08:06:23.308+0000] {logging_mixin.py:190} WARNING - Registered model 'forest_cover_logisticregression' already exists. Creating a new version of this model...
[2025-10-05T08:06:23.341+0000] {logging_mixin.py:190} WARNING - 2025/10/05 08:06:23 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: forest_cover_logisticregression, version 3
[2025-10-05T08:06:23.341+0000] {logging_mixin.py:190} WARNING - Created version '3' of model 'forest_cover_logisticregression'.
[2025-10-05T08:06:23.355+0000] {logging_mixin.py:190} WARNING - 2025/10/05 08:06:23 INFO mlflow.tracking._tracking_service.client: üèÉ View run LogisticRegression_batch_2 at: http://mlflow:5000/#/experiments/1/runs/efb9ae71398b4983aa6778872fdf52f2.
[2025-10-05T08:06:23.355+0000] {logging_mixin.py:190} WARNING - 2025/10/05 08:06:23 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow:5000/#/experiments/1.
[2025-10-05T08:06:23.370+0000] {logging_mixin.py:190} INFO - 
==================================================
[2025-10-05T08:06:23.370+0000] {logging_mixin.py:190} INFO - ‚úì Entrenamiento completado
[2025-10-05T08:06:23.371+0000] {logging_mixin.py:190} INFO -   Mejor modelo: RandomForest (Accuracy: 0.9472)
[2025-10-05T08:06:23.371+0000] {logging_mixin.py:190} INFO - ==================================================
[2025-10-05T08:06:23.371+0000] {python.py:240} INFO - Done. Returned value was: {'results': {'RandomForest': {'test_accuracy': 0.9472174411933448, 'test_f1_weighted': 0.9467905894026566, 'cv_mean_score': 0.9294320137693632, 'best_params': {'classifier__max_depth': None, 'classifier__min_samples_split': 2, 'classifier__n_estimators': 100}}, 'GradientBoosting': {'test_accuracy': 0.938324727481354, 'test_f1_weighted': 0.9380471683412301, 'cv_mean_score': 0.9230493402180149, 'best_params': {'classifier__learning_rate': 0.1, 'classifier__max_depth': 5, 'classifier__n_estimators': 100}}, 'LogisticRegression': {'test_accuracy': 0.7664945496270797, 'test_f1_weighted': 0.7560479147368506, 'cv_mean_score': 0.7648450946643718, 'best_params': {'classifier__C': 10.0, 'classifier__solver': 'saga'}}}, 'best_model': 'RandomForest', 'best_score': 0.9472174411933448, 'experiment_name': 'forest_cover_classification', 'mlflow_uri': 'http://mlflow:5000'}
[2025-10-05T08:06:23.446+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-05T08:06:23.446+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=forest_cover_mlops_pipeline, task_id=train_and_log_models, run_id=scheduled__2025-10-05T07:55:00+00:00, execution_date=20251005T075500, start_date=20251005T080121, end_date=20251005T080623
[2025-10-05T08:06:23.495+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-05T08:06:23.539+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-05T08:06:23.541+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
