[2025-10-05T03:30:11.035+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-05T03:30:11.048+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: forest_cover_mlops_pipeline.train_and_log_models scheduled__2025-10-05T03:25:00+00:00 [queued]>
[2025-10-05T03:30:11.052+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: forest_cover_mlops_pipeline.train_and_log_models scheduled__2025-10-05T03:25:00+00:00 [queued]>
[2025-10-05T03:30:11.052+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 3
[2025-10-05T03:30:11.059+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): train_and_log_models> on 2025-10-05 03:25:00+00:00
[2025-10-05T03:30:11.065+0000] {standard_task_runner.py:72} INFO - Started process 2633 to run task
[2025-10-05T03:30:11.067+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'forest_cover_mlops_pipeline', 'train_and_log_models', 'scheduled__2025-10-05T03:25:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/forest_cover_dag.py', '--cfg-path', '/home/airflow/tmp/tmpvafczzsz']
[2025-10-05T03:30:11.068+0000] {standard_task_runner.py:105} INFO - Job 37: Subtask train_and_log_models
[2025-10-05T03:30:11.102+0000] {task_command.py:467} INFO - Running <TaskInstance: forest_cover_mlops_pipeline.train_and_log_models scheduled__2025-10-05T03:25:00+00:00 [running]> on host 251551b582e0
[2025-10-05T03:30:11.404+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mlops-team-5' AIRFLOW_CTX_DAG_ID='forest_cover_mlops_pipeline' AIRFLOW_CTX_TASK_ID='train_and_log_models' AIRFLOW_CTX_EXECUTION_DATE='2025-10-05T03:25:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-05T03:25:00+00:00'
[2025-10-05T03:30:11.405+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-05T03:30:11.576+0000] {logging_mixin.py:190} INFO - Entrenando 3 modelos con GridSearchCV...
[2025-10-05T03:30:11.577+0000] {logging_mixin.py:190} INFO - 
==================================================
[2025-10-05T03:30:11.577+0000] {logging_mixin.py:190} INFO - Modelo: RandomForest
[2025-10-05T03:30:11.577+0000] {logging_mixin.py:190} INFO - ==================================================
[2025-10-05T03:30:11.594+0000] {logging_mixin.py:190} WARNING - 2025/10/05 03:30:11 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-10-05T03:30:11.661+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.11/site-packages/joblib/parallel.py:1379: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  n_jobs = self._backend.configure(

[2025-10-05T03:30:11.661+0000] {logging_mixin.py:190} INFO - Fitting 3 folds for each of 12 candidates, totalling 36 fits
[2025-10-05T03:30:57.475+0000] {logging_mixin.py:190} INFO -   Mejores par√°metros: {'classifier__max_depth': None, 'classifier__min_samples_split': 2, 'classifier__n_estimators': 100}
[2025-10-05T03:31:03.237+0000] {logging_mixin.py:190} INFO -   Train Accuracy: 1.0000
[2025-10-05T03:31:03.237+0000] {logging_mixin.py:190} INFO -   Test Accuracy: 0.9664
[2025-10-05T03:31:03.237+0000] {logging_mixin.py:190} INFO -   Test F1 (weighted): 0.9664
[2025-10-05T03:31:03.237+0000] {logging_mixin.py:190} INFO -   CV Score: 0.9560 (+/- 0.0023)
[2025-10-05T03:31:05.563+0000] {logging_mixin.py:190} WARNING - 2025/10/05 03:31:05 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-10-05T03:31:05.612+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2025-10-05T03:31:05.875+0000] {logging_mixin.py:190} WARNING - Registered model 'forest_cover_randomforest' already exists. Creating a new version of this model...
[2025-10-05T03:31:05.892+0000] {logging_mixin.py:190} WARNING - 2025/10/05 03:31:05 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: forest_cover_randomforest, version 5
[2025-10-05T03:31:05.892+0000] {logging_mixin.py:190} WARNING - Created version '5' of model 'forest_cover_randomforest'.
[2025-10-05T03:31:05.902+0000] {logging_mixin.py:190} WARNING - 2025/10/05 03:31:05 INFO mlflow.tracking._tracking_service.client: üèÉ View run RandomForest_batch_6 at: http://mlflow:5000/#/experiments/1/runs/3aaa41f20b4d4e3da0e216379d3da69b.
[2025-10-05T03:31:05.902+0000] {logging_mixin.py:190} WARNING - 2025/10/05 03:31:05 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow:5000/#/experiments/1.
[2025-10-05T03:31:05.912+0000] {logging_mixin.py:190} INFO - 
==================================================
[2025-10-05T03:31:05.912+0000] {logging_mixin.py:190} INFO - Modelo: GradientBoosting
[2025-10-05T03:31:05.912+0000] {logging_mixin.py:190} INFO - ==================================================
[2025-10-05T03:31:05.963+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.11/site-packages/joblib/parallel.py:1379: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  n_jobs = self._backend.configure(

[2025-10-05T03:31:05.963+0000] {logging_mixin.py:190} INFO - Fitting 3 folds for each of 8 candidates, totalling 24 fits
[2025-10-05T03:37:26.812+0000] {logging_mixin.py:190} INFO -   Mejores par√°metros: {'classifier__learning_rate': 0.1, 'classifier__max_depth': 5, 'classifier__n_estimators': 100}
[2025-10-05T03:38:32.829+0000] {logging_mixin.py:190} INFO -   Train Accuracy: 0.9756
[2025-10-05T03:38:32.829+0000] {logging_mixin.py:190} INFO -   Test Accuracy: 0.9511
[2025-10-05T03:38:32.829+0000] {logging_mixin.py:190} INFO -   Test F1 (weighted): 0.9511
[2025-10-05T03:38:32.829+0000] {logging_mixin.py:190} INFO -   CV Score: 0.9389 (+/- 0.0029)
[2025-10-05T03:38:34.336+0000] {logging_mixin.py:190} WARNING - 2025/10/05 03:38:34 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-10-05T03:38:34.406+0000] {logging_mixin.py:190} WARNING - Registered model 'forest_cover_gradientboosting' already exists. Creating a new version of this model...
[2025-10-05T03:38:34.422+0000] {logging_mixin.py:190} WARNING - 2025/10/05 03:38:34 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: forest_cover_gradientboosting, version 4
[2025-10-05T03:38:34.422+0000] {logging_mixin.py:190} WARNING - Created version '4' of model 'forest_cover_gradientboosting'.
[2025-10-05T03:38:34.429+0000] {logging_mixin.py:190} WARNING - 2025/10/05 03:38:34 INFO mlflow.tracking._tracking_service.client: üèÉ View run GradientBoosting_batch_6 at: http://mlflow:5000/#/experiments/1/runs/d7111876f9bf4e66b89328c8db585472.
[2025-10-05T03:38:34.429+0000] {logging_mixin.py:190} WARNING - 2025/10/05 03:38:34 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow:5000/#/experiments/1.
[2025-10-05T03:38:34.438+0000] {logging_mixin.py:190} INFO - 
==================================================
[2025-10-05T03:38:34.438+0000] {logging_mixin.py:190} INFO - Modelo: LogisticRegression
[2025-10-05T03:38:34.438+0000] {logging_mixin.py:190} INFO - ==================================================
[2025-10-05T03:38:34.488+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.11/site-packages/joblib/parallel.py:1379: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  n_jobs = self._backend.configure(

[2025-10-05T03:38:34.489+0000] {logging_mixin.py:190} INFO - Fitting 3 folds for each of 6 candidates, totalling 18 fits
[2025-10-05T03:39:05.986+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[2025-10-05T03:39:10.787+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[2025-10-05T03:39:15.105+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[2025-10-05T03:39:21.707+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[2025-10-05T03:39:21.707+0000] {logging_mixin.py:190} INFO -   Mejores par√°metros: {'classifier__C': 10.0, 'classifier__solver': 'saga'}
[2025-10-05T03:39:26.512+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[2025-10-05T03:39:31.027+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[2025-10-05T03:39:35.466+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[2025-10-05T03:39:35.469+0000] {logging_mixin.py:190} INFO -   Train Accuracy: 0.7635
[2025-10-05T03:39:35.469+0000] {logging_mixin.py:190} INFO -   Test Accuracy: 0.7664
[2025-10-05T03:39:35.469+0000] {logging_mixin.py:190} INFO -   Test F1 (weighted): 0.7574
[2025-10-05T03:39:35.469+0000] {logging_mixin.py:190} INFO -   CV Score: 0.7617 (+/- 0.0008)
[2025-10-05T03:39:36.981+0000] {logging_mixin.py:190} WARNING - 2025/10/05 03:39:36 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-10-05T03:39:37.028+0000] {logging_mixin.py:190} WARNING - Registered model 'forest_cover_logisticregression' already exists. Creating a new version of this model...
[2025-10-05T03:39:37.042+0000] {logging_mixin.py:190} WARNING - 2025/10/05 03:39:37 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: forest_cover_logisticregression, version 4
[2025-10-05T03:39:37.042+0000] {logging_mixin.py:190} WARNING - Created version '4' of model 'forest_cover_logisticregression'.
[2025-10-05T03:39:37.049+0000] {logging_mixin.py:190} WARNING - 2025/10/05 03:39:37 INFO mlflow.tracking._tracking_service.client: üèÉ View run LogisticRegression_batch_6 at: http://mlflow:5000/#/experiments/1/runs/e9691079e4b04e9398e0e276d11dc476.
[2025-10-05T03:39:37.049+0000] {logging_mixin.py:190} WARNING - 2025/10/05 03:39:37 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow:5000/#/experiments/1.
[2025-10-05T03:39:37.058+0000] {logging_mixin.py:190} INFO - 
==================================================
[2025-10-05T03:39:37.058+0000] {logging_mixin.py:190} INFO - ‚úì Entrenamiento completado
[2025-10-05T03:39:37.058+0000] {logging_mixin.py:190} INFO -   Mejor modelo: RandomForest (Accuracy: 0.9664)
[2025-10-05T03:39:37.058+0000] {logging_mixin.py:190} INFO - ==================================================
[2025-10-05T03:39:37.059+0000] {python.py:240} INFO - Done. Returned value was: {'results': {'RandomForest': {'test_accuracy': 0.9664371772805508, 'test_f1_weighted': 0.9664024327723238, 'cv_mean_score': 0.9560025817555937, 'best_params': {'classifier__max_depth': None, 'classifier__min_samples_split': 2, 'classifier__n_estimators': 100}}, 'GradientBoosting': {'test_accuracy': 0.9510900745840505, 'test_f1_weighted': 0.9510676492879154, 'cv_mean_score': 0.9389343086632244, 'best_params': {'classifier__learning_rate': 0.1, 'classifier__max_depth': 5, 'classifier__n_estimators': 100}}, 'LogisticRegression': {'test_accuracy': 0.7663511187607573, 'test_f1_weighted': 0.7573768360724669, 'cv_mean_score': 0.7617254733218588, 'best_params': {'classifier__C': 10.0, 'classifier__solver': 'saga'}}}, 'best_model': 'RandomForest', 'best_score': 0.9664371772805508, 'experiment_name': 'forest_cover_classification', 'mlflow_uri': 'http://mlflow:5000'}
[2025-10-05T03:39:37.089+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-05T03:39:37.089+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=forest_cover_mlops_pipeline, task_id=train_and_log_models, run_id=scheduled__2025-10-05T03:25:00+00:00, execution_date=20251005T032500, start_date=20251005T033011, end_date=20251005T033937
[2025-10-05T03:39:37.138+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-05T03:39:37.158+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-05T03:39:37.159+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
