[2025-10-05T08:21:16.184+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-05T08:21:16.196+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: forest_cover_mlops_pipeline.train_and_log_models scheduled__2025-10-05T08:15:00+00:00 [queued]>
[2025-10-05T08:21:16.200+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: forest_cover_mlops_pipeline.train_and_log_models scheduled__2025-10-05T08:15:00+00:00 [queued]>
[2025-10-05T08:21:16.200+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 3
[2025-10-05T08:21:16.206+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): train_and_log_models> on 2025-10-05 08:15:00+00:00
[2025-10-05T08:21:16.212+0000] {standard_task_runner.py:72} INFO - Started process 3334 to run task
[2025-10-05T08:21:16.214+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'forest_cover_mlops_pipeline', 'train_and_log_models', 'scheduled__2025-10-05T08:15:00+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/forest_cover_dag.py', '--cfg-path', '/home/airflow/tmp/tmpiq9u4zxs']
[2025-10-05T08:21:16.215+0000] {standard_task_runner.py:105} INFO - Job 82: Subtask train_and_log_models
[2025-10-05T08:21:16.271+0000] {task_command.py:467} INFO - Running <TaskInstance: forest_cover_mlops_pipeline.train_and_log_models scheduled__2025-10-05T08:15:00+00:00 [running]> on host 3702e9b7dcde
[2025-10-05T08:21:16.645+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mlops-team' AIRFLOW_CTX_DAG_ID='forest_cover_mlops_pipeline' AIRFLOW_CTX_TASK_ID='train_and_log_models' AIRFLOW_CTX_EXECUTION_DATE='2025-10-05T08:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-05T08:15:00+00:00'
[2025-10-05T08:21:16.645+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-05T08:21:16.803+0000] {logging_mixin.py:190} INFO - Entrenando 3 modelos con GridSearchCV...
[2025-10-05T08:21:16.803+0000] {logging_mixin.py:190} INFO - 
==================================================
[2025-10-05T08:21:16.804+0000] {logging_mixin.py:190} INFO - Modelo: RandomForest
[2025-10-05T08:21:16.804+0000] {logging_mixin.py:190} INFO - ==================================================
[2025-10-05T08:21:16.820+0000] {logging_mixin.py:190} WARNING - 2025/10/05 08:21:16 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-10-05T08:21:16.868+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.11/site-packages/joblib/parallel.py:1379: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  n_jobs = self._backend.configure(

[2025-10-05T08:21:16.868+0000] {logging_mixin.py:190} INFO - Fitting 3 folds for each of 12 candidates, totalling 36 fits
[2025-10-05T08:22:01.434+0000] {logging_mixin.py:190} INFO -   Mejores par√°metros: {'classifier__max_depth': None, 'classifier__min_samples_split': 2, 'classifier__n_estimators': 100}
[2025-10-05T08:22:06.972+0000] {logging_mixin.py:190} INFO -   Train Accuracy: 1.0000
[2025-10-05T08:22:06.972+0000] {logging_mixin.py:190} INFO -   Test Accuracy: 0.9686
[2025-10-05T08:22:06.972+0000] {logging_mixin.py:190} INFO -   Test F1 (weighted): 0.9684
[2025-10-05T08:22:06.972+0000] {logging_mixin.py:190} INFO -   CV Score: 0.9558 (+/- 0.0045)
[2025-10-05T08:22:09.140+0000] {logging_mixin.py:190} WARNING - 2025/10/05 08:22:09 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-10-05T08:22:09.189+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2025-10-05T08:22:09.561+0000] {logging_mixin.py:190} WARNING - Registered model 'forest_cover_randomforest' already exists. Creating a new version of this model...
[2025-10-05T08:22:09.579+0000] {logging_mixin.py:190} WARNING - 2025/10/05 08:22:09 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: forest_cover_randomforest, version 6
[2025-10-05T08:22:09.579+0000] {logging_mixin.py:190} WARNING - Created version '6' of model 'forest_cover_randomforest'.
[2025-10-05T08:22:09.591+0000] {logging_mixin.py:190} WARNING - 2025/10/05 08:22:09 INFO mlflow.tracking._tracking_service.client: üèÉ View run RandomForest_batch_5 at: http://mlflow:5000/#/experiments/1/runs/b88fedf210c546a3aa5bdbc51e668dfb.
[2025-10-05T08:22:09.591+0000] {logging_mixin.py:190} WARNING - 2025/10/05 08:22:09 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow:5000/#/experiments/1.
[2025-10-05T08:22:09.603+0000] {logging_mixin.py:190} INFO - 
==================================================
[2025-10-05T08:22:09.603+0000] {logging_mixin.py:190} INFO - Modelo: GradientBoosting
[2025-10-05T08:22:09.604+0000] {logging_mixin.py:190} INFO - ==================================================
[2025-10-05T08:22:09.743+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.11/site-packages/joblib/parallel.py:1379: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  n_jobs = self._backend.configure(

[2025-10-05T08:22:09.743+0000] {logging_mixin.py:190} INFO - Fitting 3 folds for each of 8 candidates, totalling 24 fits
[2025-10-05T08:28:20.533+0000] {logging_mixin.py:190} INFO -   Mejores par√°metros: {'classifier__learning_rate': 0.1, 'classifier__max_depth': 5, 'classifier__n_estimators': 100}
[2025-10-05T08:29:29.608+0000] {logging_mixin.py:190} INFO -   Train Accuracy: 0.9751
[2025-10-05T08:29:29.608+0000] {logging_mixin.py:190} INFO -   Test Accuracy: 0.9481
[2025-10-05T08:29:29.608+0000] {logging_mixin.py:190} INFO -   Test F1 (weighted): 0.9480
[2025-10-05T08:29:29.608+0000] {logging_mixin.py:190} INFO -   CV Score: 0.9403 (+/- 0.0049)
[2025-10-05T08:29:31.085+0000] {logging_mixin.py:190} WARNING - 2025/10/05 08:29:31 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-10-05T08:29:31.218+0000] {logging_mixin.py:190} WARNING - Registered model 'forest_cover_gradientboosting' already exists. Creating a new version of this model...
[2025-10-05T08:29:31.284+0000] {logging_mixin.py:190} WARNING - 2025/10/05 08:29:31 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: forest_cover_gradientboosting, version 6
[2025-10-05T08:29:31.285+0000] {logging_mixin.py:190} WARNING - Created version '6' of model 'forest_cover_gradientboosting'.
[2025-10-05T08:29:31.320+0000] {logging_mixin.py:190} WARNING - 2025/10/05 08:29:31 INFO mlflow.tracking._tracking_service.client: üèÉ View run GradientBoosting_batch_5 at: http://mlflow:5000/#/experiments/1/runs/fc587f3ea2ca43fcb947a9cbe7fefbca.
[2025-10-05T08:29:31.321+0000] {logging_mixin.py:190} WARNING - 2025/10/05 08:29:31 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow:5000/#/experiments/1.
[2025-10-05T08:29:31.358+0000] {logging_mixin.py:190} INFO - 
==================================================
[2025-10-05T08:29:31.358+0000] {logging_mixin.py:190} INFO - Modelo: LogisticRegression
[2025-10-05T08:29:31.359+0000] {logging_mixin.py:190} INFO - ==================================================
[2025-10-05T08:29:31.508+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.11/site-packages/joblib/parallel.py:1379: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  n_jobs = self._backend.configure(

[2025-10-05T08:29:31.509+0000] {logging_mixin.py:190} INFO - Fitting 3 folds for each of 6 candidates, totalling 18 fits
[2025-10-05T08:30:02.789+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[2025-10-05T08:30:07.402+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[2025-10-05T08:30:12.533+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[2025-10-05T08:30:19.850+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[2025-10-05T08:30:19.850+0000] {logging_mixin.py:190} INFO -   Mejores par√°metros: {'classifier__C': 10.0, 'classifier__solver': 'saga'}
[2025-10-05T08:30:24.552+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[2025-10-05T08:30:29.535+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[2025-10-05T08:30:34.400+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[2025-10-05T08:30:34.402+0000] {logging_mixin.py:190} INFO -   Train Accuracy: 0.7651
[2025-10-05T08:30:34.402+0000] {logging_mixin.py:190} INFO -   Test Accuracy: 0.7645
[2025-10-05T08:30:34.403+0000] {logging_mixin.py:190} INFO -   Test F1 (weighted): 0.7549
[2025-10-05T08:30:34.403+0000] {logging_mixin.py:190} INFO -   CV Score: 0.7649 (+/- 0.0039)
[2025-10-05T08:30:36.026+0000] {logging_mixin.py:190} WARNING - 2025/10/05 08:30:36 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-10-05T08:30:36.097+0000] {logging_mixin.py:190} WARNING - Registered model 'forest_cover_logisticregression' already exists. Creating a new version of this model...
[2025-10-05T08:30:36.150+0000] {logging_mixin.py:190} WARNING - 2025/10/05 08:30:36 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: forest_cover_logisticregression, version 6
[2025-10-05T08:30:36.150+0000] {logging_mixin.py:190} WARNING - Created version '6' of model 'forest_cover_logisticregression'.
[2025-10-05T08:30:36.165+0000] {logging_mixin.py:190} WARNING - 2025/10/05 08:30:36 INFO mlflow.tracking._tracking_service.client: üèÉ View run LogisticRegression_batch_5 at: http://mlflow:5000/#/experiments/1/runs/40f37aaeda6a47b1a9ed4736ad7d3e44.
[2025-10-05T08:30:36.165+0000] {logging_mixin.py:190} WARNING - 2025/10/05 08:30:36 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow:5000/#/experiments/1.
[2025-10-05T08:30:36.183+0000] {logging_mixin.py:190} INFO - 
==================================================
[2025-10-05T08:30:36.184+0000] {logging_mixin.py:190} INFO - ‚úì Entrenamiento completado
[2025-10-05T08:30:36.184+0000] {logging_mixin.py:190} INFO -   Mejor modelo: RandomForest (Accuracy: 0.9686)
[2025-10-05T08:30:36.184+0000] {logging_mixin.py:190} INFO - ==================================================
[2025-10-05T08:30:36.184+0000] {python.py:240} INFO - Done. Returned value was: {'results': {'RandomForest': {'test_accuracy': 0.9685886402753873, 'test_f1_weighted': 0.9684404241644055, 'cv_mean_score': 0.9557515777395295, 'best_params': {'classifier__max_depth': None, 'classifier__min_samples_split': 2, 'classifier__n_estimators': 100}}, 'GradientBoosting': {'test_accuracy': 0.9480780263912794, 'test_f1_weighted': 0.9480037798313112, 'cv_mean_score': 0.9402969018932875, 'best_params': {'classifier__learning_rate': 0.1, 'classifier__max_depth': 5, 'classifier__n_estimators': 100}}, 'LogisticRegression': {'test_accuracy': 0.7644865174985657, 'test_f1_weighted': 0.7548713599957976, 'cv_mean_score': 0.7648809523809524, 'best_params': {'classifier__C': 10.0, 'classifier__solver': 'saga'}}}, 'best_model': 'RandomForest', 'best_score': 0.9685886402753873, 'experiment_name': 'forest_cover_classification', 'mlflow_uri': 'http://mlflow:5000'}
[2025-10-05T08:30:36.234+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-05T08:30:36.235+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=forest_cover_mlops_pipeline, task_id=train_and_log_models, run_id=scheduled__2025-10-05T08:15:00+00:00, execution_date=20251005T081500, start_date=20251005T082116, end_date=20251005T083036
[2025-10-05T08:30:36.286+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-05T08:30:36.310+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-05T08:30:36.311+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
